### PR TITLE
Fix #542: Reduce duplicity and improve exception handling in ActivationService

### LINKED ISSUE #542: Reduce duplicity and improve exception handling in ActivationService

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

File: powerauth-restful-security-spring/src/main/java/io/getlime/security/powerauth/rest/api/spring/service/ActivationService.java [hunk 1]
```diff
@@ -459,28 +447,23 @@ public ActivationLayer1Response createActivation(ActivationLayer1Request request
...
             if (ex.getPowerAuthError().orElse(null) instanceof final PowerAuthErrorRecovery errorRecovery) {
                 logger.debug("Invalid recovery code, current PUK index: {}", errorRecovery.getCurrentRecoveryPukIndex());
                 throw new PowerAuthRecoveryException(ex.getMessage(), "INVALID_RECOVERY_CODE", errorRecovery.getCurrentRecoveryPukIndex());
             }
-            logger.warn("Creating PowerAuth activation failed, error: {}", ex.getMessage());
-            logger.debug(ex.getMessage(), ex);
-            throw new PowerAuthActivationException();
-        } catch (PowerAuthActivationException ex) {
-            // Do not swallow PowerAuthActivationException for custom activations.
-            // See: https://github.com/wultra/powerauth-restful-integration/issues/199
```
Comment (banterCZ) [inline powerauth-restful-security-spring/src/main/java/io/getlime/security/powerauth/rest/api/spring/service/ActivationService.java:477]: The exception is not swallowed but passed as a cause and logged by `PowerAuthExceptionHandler`.

**Review by romanstrobl — APPROVED** [review]
Looks OK.

**Review by jnpsk — APPROVED** [review]
looks ok
